services:
  - type: web
    name: telegram-sms-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
  
  - type: worker
    name: telegram-sms-forwarder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_forwarder_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 